### ISSUE TITLE
GetActions: Proxy Transport request to an extension

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#106]
- Transport request landing up on ExtensionsOrchestrator will proxy the request to SDK
- SDK to understand the transport action request and respond.

**Comment by owaiskazi19** [comment]
Hey @saratvemulapalli! Thanks for the PR for this issue. Should we add more details in this issue to address the work? This will help to review the PR?

**Comment by dbwiddis** [comment]
@saratvemulapalli does my issue #152 duplicate this functionality?

**Comment by saratvemulapalli** [comment]
> #152
@dbwiddis looks like we need the same framework which we've built for transport actions. 
Probably we'd want to make it generic. I can take this up after the priority issues are taken care of.
