### ISSUE TITLE
GetActions: Add support to dynamically register actions

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#107]
- Dynamically register transport actions in ActionModule

Transport Actions in extensions are registered with ExtensionsManager via Proxy Actions. But eventually we need make `ActionModule` dynamic to help register/de-register with OpenSearch

**Comment by minalsha** [comment]
This is also needed in future for hot-swap, right?

**Comment by owaiskazi19** [comment]
> This is also needed in future for hot-swap, right?

Yes

**Comment by dbwiddis** [comment]
Right now transport actions are registered in a map which is:
 - final
 - unmodifiable

Sarat's draft PR linked above removed the unmodifiable bit for that map.  However, I'm going to approach this in #525 by just adding a second dynamic map, and integrate the `transportAction(action)` method to check both maps.  Other than that the implementation will be similar to the draft PR.
