### ISSUE TITLE
[FEATURE] SDK package organization

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#126]
### Is your feature request related to a problem?

We haven't clearly articulated where packages go. Currently they accrue in the top level package until we get enough duplicates that we think they should go elsewhere.  We're there again.

### What solution would you like?

My preference is for `org.opensearch.sdk` to contain all, and only, the interfaces and classes that are part of the SDK / API that developers will need to write an extension.  Currently that is:
 - `Extension` interface
 - `ExtensionRestHandler` interface
 - `ExtensionSettings` class
 - `ExtensionsRunner` class
 - `ExtensionRestResponse` class
 - `SDKClient`

We have a `handler` subpackage that is well defined.

We should figure out how to organize:
 - `ExtensionRestPathRegistry`
 - `NamedWriteableRegistryAPI`
 - `ActionListener`
 - `TransportActions`

I'm thinking a `transport` or `registry` or something might be useful here. Seeking input!

### What alternatives have you considered?

Rest package, but I think a lot of the "Rest" named classes belong in the root

**Comment by owaiskazi19** [comment]
On top of my mind. I can think of having `registry` for `TransportActions`, `ExtensionRestPathRegistry` and `NamedWriteableRegistryAPI`. `ActionListener ` should go in the `transport` subpackage.

**Comment by minalsha** [comment]
dup of #168
