### ISSUE TITLE
Rename this project to `opensearch-extensions` or `opensearch-extensions-java`

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-sdk-java#13]
This project is named `opensearch-sdk` and that name is pretty broad, while this is an OpenSearch specific repository, it seems to be focused on an extensibility sdk based on the content in the readme.

In the future there might be rust/go/node/... extensions software development kits to help make extensions more easily which would be named `opensearch-extensions-rs`

What do you guys think?

**Comment by dbwiddis** [comment]
The extension points should be language agnostic. It shouldn't matter what language an extension is written in, if it follows the appropriate API.   I think naming it "extensions" actually gives the impression that the extensions themselves would be developed in this project. 

I agree sdk is a bit too vague, though.  What about `opensearch-extension-sdk` or `opensearch-plugin-sdk`?

**Comment by peternied** [comment]
I like opensearch-plugin-sdk +1 for that name.

**Comment by peternied** [comment]
> The extension points should be language agnostic. 

While the extensions interface is via Rest API, there could be SDKs available in many different language implementations, such as how there are many OpenSearch client implementations in other programming languages.

**Comment by owaiskazi19** [comment]
I am fine with `opensearch-extension-sdk` as it briefly describes sdk for extensibility. In the future, we will be supporting SDK with other languages, for which we can name them as `opensearch-extension-sdk-rs`, `opensearch-extension-sdk-js` etc.

**Comment by peternied** [comment]
This issue has been a little stagnate, do one of the maintainers want to drive this rename or call it off?

**Comment by saratvemulapalli** [comment]
I am not really torn as long its named `sdk`. 
I see we have a bunch of options:

- opensearch-extensions
- opensearch-extensions-java
- openearch-sdk-java
- opensearch-extension-sdk

If i have to choose I'll go with `opensearch-sdk-java`. 
Folks put in your vote and lets take a call in 2 weeks. (Aug 12)
@peternied @dbwiddis @owaiskazi19

**Comment by owaiskazi19** [comment]
> If i have to choose I'll go with `opensearch-sdk-java`. Folks put in your vote and lets take a call in 2 weeks. (Aug 12) @peternied @dbwiddis @owaiskazi19

`opensearch-sdk-java`

**Comment by peternied** [comment]
`opensearch-sdk-java` +1

**Comment by dbwiddis** [comment]
opensearch-sdk-java +2

**Comment by dblock** [comment]
Sold!

**Comment by saratvemulapalli** [comment]
@vibrantvarun can you pick this up and rename everything to `opensearch-sdk-java`?

**Comment by owaiskazi19** [comment]
@mloufra will pick this up

**Comment by owaiskazi19** [comment]
Done!

**Comment by saratvemulapalli** [comment]
@mloufra @owaiskazi19 do we have to rename anything in the code? 
I can see the gradle project[1] has to be. Probably there are others? 

[1] https://github.com/opensearch-project/opensearch-sdk-java/blob/main/settings.gradle#L1

**Comment by dbwiddis** [comment]
> Probably there are others?

https://github.com/opensearch-project/opensearch-sdk-java/blob/0727269bee55fe59a10df6ad624fa14cad9d4b1c/DEVELOPER_GUIDE.md?plain=1#L22

This one I'm changing as part of my PR #74. It must match the name in the `extension.yml` file until #93 is complete.
https://github.com/opensearch-project/opensearch-sdk-java/blob/0727269bee55fe59a10df6ad624fa14cad9d4b1c/DEVELOPER_GUIDE.md?plain=1#L76

https://github.com/opensearch-project/opensearch-sdk-java/blob/0727269bee55fe59a10df6ad624fa14cad9d4b1c/DEVELOPER_GUIDE.md?plain=1#L168-L190

**Comment by owaiskazi19** [comment]
> @mloufra @owaiskazi19 do we have to rename anything in the code? I can see the gradle project[1] has to be. Probably there are others?
> 
> [1] https://github.com/opensearch-project/opensearch-sdk-java/blob/main/settings.gradle#L1

That's a miss. Thanks @saratvemulapalli and @dbwiddis for bringing this up. @mloufra will look into it.
