### ISSUE TITLE
Clean up compiler warnings

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#130]
Some code on `main` is producing compiler warnings and should be cleaned up so I don't see so many ⚠️s in my IDE.
 - [x] TransportActions.java `Class` on line 29 needs type arguments. (`Class<? extends TransportAction<? extends ActionRequest, ? extends ActionResponse>>>`).  This will need a simultaneous change to OpenSearch project `feature/extensions` branch `RegisterTransportActionsRequest` constructor (and associated instance variable).
 - [x] TransportAction.java `HashMap` on line 38 needs a diamond operator (`<>`)
 - [ ] NamedWriteableRegistryApi.java lines 84 and 107 need generic types for the `Class` (probably `<? extends NamedWritable>`). This will need a simultaneous change to OpenSearch project `feature/extensions` branch `NamedWriteable RegistryParseRequest` to change the type of `categoryClass` to add the same generics.
 - [x] SDKClient.java has an unused `logger`. Either log something or remove it.
 - [x] TestNamedWriteable.java has an unused inner class constructor `Example(String message)`.  I suspect this means there's missing tests somewhere.
 - [x] Unused field `extensionsRunner` in `NettyTransport` (probably the result of a merge conflict resolution)

**Comment by dbwiddis** [comment]
FYI, just noticed this in gradle check logs:
> Note: /home/runner/work/opensearch-sdk-java/opensearch-sdk-java/src/main/java/org/opensearch/sdk/ExtensionNamedWriteableRegistry.java uses unchecked or unsafe operations.

I believe that fixing this issue will resolve this warning.

**Comment by mloufra** [comment]
> * [ ]  TransportActions.java `Class` on line 29 needs type arguments. (`Class<? extends TransportAction<? extends ActionRequest, ? extends ActionResponse>>>`).  This will need a simultaneous change to OpenSearch project `feature/extensions` branch `RegisterTransportActionsRequest` constructor (and associated instance variable).

Can we use `@SuppressWarnings(“rawtypes”)` to ignore compiler warning for clean up purpose?

**Comment by owaiskazi19** [comment]
> Can we use `@SuppressWarnings(“rawtypes”)` to ignore compiler warning for clean up purpose?

Hey @mloufra! SuppressWarnings is used to ignore the warnings. We don't have to ignore them but to resolve them. We need to add a type argument by making the change in OpenSearch repo's `feature/extensions` branch `RegisterTransportActionsRequest` constructor.

**Comment by dbwiddis** [comment]
> Can we use `@SuppressWarnings(“rawtypes”)` to ignore compiler warning for clean up purpose?

As a follow-up, there are cases in `Writeable` objects using the `StreamInput` constructor where we are using `Class.forName()` to generate the class and don't have the type information as part of that (writeable String).  In those cases, cast the returned `Class` to the appropriate type, and it is acceptable if you have double- and triple-checked that the signature matches the class in `writeTo()`, to add the `@SuppressWarnings("unchecked")` annotation for this unchecked cast.
