### ISSUE TITLE
[FEATURE] Integrate the local published SDK with AD 

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#133]
### Is your feature request related to a problem?
1. Integrate the local published SDK with AD build.gradle
2. Create a main class to use the imported code available from SDK.

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by minalsha** [comment]
#137 dependency
