### ISSUE TITLE
[FEATURE] Replacement of `opensearchplugin` for Extensions

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#137]
### Is your feature request related to a problem?
In the current plugin architecture, plugin depends on [`opensearchplugin`](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L93) which provides OpenSearch with the [information](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L121) required to run the plugin after the installation. Later, the attributes defined in build.gradle like [`publishing`](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L153), [`bundlePlugin`](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L229),  [`integTest`](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L221) are fetch from OpenSearch and depends on the same.

Since Extensions will be running independently these tasks can't be fetch from OpenSearch because we will be removing the `opensearchplugin`. 

### What solution would you like?
1. Create a similar gradle plugin like `opensearchplugin` named `opensearchextension` to fetch the dependencies and add an `application` plugin in the build.gradle file of the extension to run the main class directly.
2. Figure out a way to remove the dependencies from OpenSearch and run the above mentioned tasks independently in the SDK.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
I vote against option 1.   Which I suppose means I support option 2, although I'm not sure what that looks like yet.

We need to imagine a future filled with thousands of extensions, the overwhelming majority of which are not part of our own build ecosystem.  They will be on various GitHub, GitLab, BitBucket, and other repos which we only really see when they are published on a (or "The") Central Repository.  Some may be private for corporate use that we may never see.  Some will live on the local desktop of some enterprising young developer cutting their teeth on extensions in between their middle school homework assignments who may never commit it anywhere but will want to play with the best distributed search platform on the planet and maybe imagine a cool new feature that they eventually contribute here.

Whatever solution we develop needs to run completely independently of our own gradle builds.

**Comment by owaiskazi19** [comment]
Hi @dbwiddis! I got the extension working independently. The only task remaining is set up our test cluster for integration tests since we can't use the one provided by OpenSearch. The issue https://github.com/opensearch-project/opensearch-sdk-java/issues/120 will be required to close this out.

**Comment by dbwiddis** [comment]
Great job!

**Comment by saratvemulapalli** [comment]
Thanks @owaiskazi19. I think we have to think about the tooling which exists around plugins but it necessarily doesnt mean we have to replicate it for extensions. A lot of pieces do not apply and we strive to remove the coupling unless its really needed.
