### ISSUE TITLE
Incorporate SDK design and integrate AnomalyDetection Indices

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#160]
### Is your feature request related to a problem?
Initialize `searchFeatureDao`, `anomalyDetectionIndices`, `adTaskManager` objects using the Transport APIs created [here](https://github.com/opensearch-project/opensearch-sdk-java/issues/78). 

The following items have been completed for the above objects:

 

- [X] Change constructors to match SDK createComponents method
- [X]  Replace environmentSettings calls with new API
- [X]  Replace AdSettingConsumer calls with new API
- [X]  Remove clusterService and replace functionality
- [X]  Replace client index and delete requests in AnomalyDetectionIndices.java]
- [X] Replace all adminClient create requests in AnomalyDetectionIndices.java
- [X]  Replace adminClient clusterState request in AnomalyDetectionIndices.java
- [X]  Replace adminClient getAliases() and rolloverIndexRequest() in AnomalyDetectionIndices.java
- [X]  Remove ActionListener from AnomalyDetectionIndices.java

Remaining tasks:
- [ ]  Replace adminClient putMapping() in AnomalyDetectionIndices.java
- [ ]  Research how to use the SearchResponse from SDK client as a replacement for NodeClient for search requests in SearchFeatureDao.java and AdTaskManager.java
- [ ]  Replace all client calls in SearchFeatureDao.java, AdTaskManager.java, and HashRing.java

**Comment by ryanbogan** [comment]
The following items have been completed for the above objects:

- [ ] Change constructors to match SDK createComponents method
- [ ] Replace environmentSettings calls with new API
- [ ] Replace AdSettingConsumer calls with new API
- [ ] Remove clusterService and replace functionality
- [ ] Replace client index and delete requests in `AnomalyDetectionIndices.java`

Remaining tasks:

- [ ] Replace all adminClient create requests in `AnomalyDetectionIndices.java`

- [ ] Replace adminClient clusterState request in `AnomalyDetectionIndices.java`
- [ ] Replace adminClient `getAliases()` and `rolloverIndexRequest()` in `AnomalyDetectionIndices.java`
- [ ] Research how to use the SearchResponse from SDK client as a replacement for NodeClient for search requests in `SearchFeatureDao.java` and `AdTaskManager.java`
- [ ] Replace all client calls in `SearchFeatureDao.java` and `AdTaskManager.java`

**Comment by minalsha** [comment]
@ryanbogan is there a draft PR for workitems completed for this? If so, could you please provide a link to it. Thanks

**Comment by dbwiddis** [comment]
> @ryanbogan is there a draft PR for workitems completed for this? If so, could you please provide a link to it. Thanks

@minalsha here's the PR: https://github.com/opensearch-project/anomaly-detection/pull/684

I'm closing this issue as I've integrated everything from this issue and that draft PR, except for the HashRing which is covered by #283
