### ISSUE TITLE
How should OpenSearch allow for extensions to provide authentication? 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-sdk-java#19]
Today there are [HTTPAuthenticator.java](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/HTTPAuthenticator.java) and [AuthenticationBackend.java](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/AuthenticationBackend.java) which are extensible through the security plugin for OpenSearch.  There are existing implementations for internal user storage, kerberos, saml, ldap, and jwt exchange,   The dependency on the Security plugin interfaces does not seem like the correct long term solution for extensions that want to provide authentication.

As many customers have existing Identity Providers (IdP) they can leverage how should we support these with extensions.  Alternatively, should these be supported in another way perhaps built into OpenSearch?

**Comment by dbwiddis** [comment]
Closing this issue as it is being tracked by https://github.com/opensearch-project/security/issues/1895 and https://github.com/opensearch-project/OpenSearch/issues/3846
