### ISSUE TITLE
License Header Update

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#194]
### Is your feature request related to a problem?

Our license header doesn't include the Copyright lines as indicated in https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#java

I blame whoever submitted #51 for not doing it right. :-)

Also there's a stray `license` directory with some old netty licenses in it that needs to be removed.

### What solution would you like?

Update the license header per above link.  It's a simple template change in Spotless, and from there we have two choice:
 - Accept the pain of a one-time rewrite of all headers
 - Use `ratchetFrom` functionality to only apply spotless to changed files.   Since all files in the repo are already compliant, this should work just fine, and will update the headers on files as we change them over time:
```
spotless {
  ratchetFrom 'origin/main' // only format files which have changed since origin/main
```

### What alternatives have you considered?
Leaving the license as-is.  Copyright statements aren't technically required. But we should be consistent!

### Do you have any additional context?

We should also discuss whether we want a blank line between the license header and `package` declaration.

**Comment by saratvemulapalli** [comment]
@dbwiddis I spent some CPU cycles around this. 
I'd like us to be consistent across the project as our recommendation: https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#license-headers
I hate to say one time effort but I feel thats the better approach to clean up and let spotless take it from there for all future files.
