### ISSUE TITLE
[META] Create Transport APIs for the dependencies of OpenSearch for creating detector

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#21]
### Is your feature request related to a problem?
Create Transport Request/Response for the below and check if they are accessible in SDK
1. [ClusterService](https://github.com/opensearch-project/opensearch-sdk/issues/47)
2. [NamedXContentRegistry](https://github.com/opensearch-project/opensearch/issues/3379) -  XContentRegistry not used in createDetector
4. [ActionListener](https://github.com/opensearch-project/opensearch-sdk/issues/61)

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by saratvemulapalli** [comment]
Based on the work done in #20 I've added the extension points to support.
