### ISSUE TITLE
[META] Implement Get Detector for AnomalyDetector Extension

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#211]
### Is your feature request related to a problem?
Since we have the first feature up [here](https://github.com/opensearch-project/anomaly-detection/pull/692) for creating a detector. 
Old plugin APIs for Get Detector:
```
1. GET _plugins/_anomaly_detection/detectors/<detectorId>
2. GET _plugins/_anomaly_detection/detectors/<detectorId>?job=true
```
This issue addresses the 1st request as 2nd has dependency on Job Scheduler. Until we finish the integration of Job Scheduler with AD Extension we can't start working on 2nd.

The proposed API for Get Detector with extensibility:
```
GET _extensions/_anomaly_detection/detectors/<detectorId>
```

The next milestone is to implement an API to get the detector which has already been created. The feature can be broken down as below:
1. Currently the detector id is not randomized and is a pure string in the response of create detector - https://github.com/opensearch-project/opensearch-sdk-java/issues/212
2. Create a Rest Handler to add GET method for the detector. - https://github.com/opensearch-project/opensearch-sdk-java/issues/213
3. Implement the logic for searching the detector. - https://github.com/opensearch-project/opensearch-sdk-java/issues/214
4. Create the response for Get Detector similar to old plugin architecture response.  - https://github.com/opensearch-project/opensearch-sdk-java/issues/215

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
How are we tracking the job scheduler one?  Separate meta issue for job scheduler integration, or should we list it here knowing we can't do it yet?

**Comment by owaiskazi19** [comment]
> How are we tracking the job scheduler one? Separate meta issue for job scheduler integration, or should we list it here knowing we can't do it yet?

That's a good point. I am thinking of creating an issue and adding such features which are dependent on Job Scheduler there.

**Comment by owaiskazi19** [comment]
Covered this issue in #373 and #451
