### ISSUE TITLE
[FEATURE] Create a Rest Handler to add GET method for the detector

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#213]
### Is your feature request related to a problem?
Similar to the Rest Handler created for Create Detector or Hello World Extension, create an action implementing `ExtensionRestHandler` with routes for the get detector API calls handled by appropriate methods with placeholder code:
```
GET detectors/{detectorId}
GET detectors/{detectorId}?job=true
```

Java code:
```
private ExtensionRestResponse handleGetRequest(ExtensionRestRequest request) {
    // do things with request
    return new ExtensionRestResponse(request, OK, "placeholder");
}}
```

Create a GET Rest handler for get detector similar to [this](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/RestGetAnomalyDetectorAction.java#L57). The business logic will be later done in #214

**Comment by mloufra** [comment]
- [ ] Create `RestGetDetectorAction.java` placed in AnomalyDetector repository feature/extensions branch
- [ ] Add `Route` method 
- [ ] Add `handleGetRequest` method
