### ISSUE TITLE
[FEATURE] Create a Rest Handler to add POST _validate/detector method

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#221]
### Is your feature request related to a problem?
Similar to the Rest Handler created for Create Detector or Hello World Extension or GET method in #213, create an action implementing `ExtensionRestHandler` with routes for the validate detector API calls handled by appropriate methods with placeholder code:
```
POST /detectors/_validate
POST /detectors/_validate/{type}
```

Java code:
```
private ExtensionRestResponse handleValidateDetectorRequest(ExtensionRestRequest request) {
    // do things with request
    return new ExtensionRestResponse(request, OK, "placeholder");
}
```

Create a POST _validate Rest handler for validate detector similar to [this](https://github.com/opensearch-project/anomaly-detection/blob/ca905f15355594a1e354f4a1da7c07a893af2211/src/main/java/org/opensearch/ad/rest/RestValidateAnomalyDetectorAction.java#L105). The business logic will be later done in #222.

**Comment by mloufra** [comment]
- [  ] Create `RestValidateDetectorAction.java` placed in AnomalyDetector repository feature/extensions branch
- [  ] Add `Route` method 
- [  ] Add `handleValidateDetectorRequest` method 
- [  ] Add Post_Validate action to the list of Rest Handlers in the `AnomalyDetectorExtension.java`

**Comment by dbwiddis** [comment]
I like the checkbox status comment!

**Comment by dbwiddis** [comment]
Completed in [AD #732](https://github.com/opensearch-project/anomaly-detection/pull/732)
