### ISSUE TITLE
[DISCUSS] Reduce approving reviewers to 1 for merging PRs

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#255]
### What are you proposing?

Our current configuration of 2 approving reviewers, combined with invalidating reviews on any pushes, is creating unnecessary friction for the review process.  Of five active [maintainers](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/MAINTAINERS.md) we are encountering situations where vacation and on-call duties reduce those able to look at PRs to 3; since the submitter cannot approve their own PR that means the other two must review.  Typo fixes or documentation suggestions invalidate reviews causing unneeded re-reviews just to satisfy the configuration.

I am proposing:
 - reducing the approving limit to 1 in the github configuration, but
 - PR submitters should request reviews from those maintainers best suited to understand their code
   - other reviewers can add to this list
   - we should keep a policy that all those who were requested to review have reviewed at least once, even if it was invalidated

I'll find the appropriate place to document this (CONTRIBUTING, probably) once it's agreed on. 

### What users have asked for this feature?

A majority of current maintainers have discussed slow approval and determined this is a good suggestion, pending input of others such as @dblock and @peternied and @minalsha .

### What problems are you trying to solve?

PRs taking too long to review, slowing development pace, increasing friction, and creating distractions.

**Comment by peternied** [comment]
> Typo fixes or documentation suggestions invalidate reviews causing unneeded **re-reviews** just to satisfy the configuration.

What do you think about unchecking`Dismiss stale pull request approvals when new commits are pushed` so approvals can be given while allowing flexibility for updates without explicit sign off on every commit?

**Comment by dbwiddis** [comment]
> What do you think about unchecking`Dismiss stale pull request approvals when new commits are pushed` so approvals can be given while allowing flexibility for updates without explicit sign off on every commit?

If there was any ability to filter that checkbox to differentiate a documentation fix vs. a code change, I'd be all over that.  However, I think we want to keep that config for code changes.  (Although a merge commit doesn't invalidate and you can do all sorts of fun stuff while rebasing!)

Ultimately we have to trust the final approver to  look at the approval history and make a subjective call.  I'd rather that subjective call be in the context of "we want the right people to have reviewed this PR" rather than a subjective call of trying to see what code changes were done after the last review and guessing whether they require review invalidation.

**Comment by peternied** [comment]
@dbwiddis Sounds like you know your requirements pretty well.  Maybe you could experiment with it for a couple of weeks and then do a retro and let folks know.  I'd be interested in what you discover.

**Comment by peternied** [comment]
@dbwiddis Did you have any findings on how your maintainers liked / didn't like the settings?

**Comment by dbwiddis** [comment]
We ended up staying where we are.  The issue we were facing is a temporary one and we've improved our communication of need for review.
