### ISSUE TITLE
[Extensions] Enable extensions to provide job index names and job types to Job Scheduler after JS is bootstraped by PluginsService

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/opensearch-sdk-java#262]

**Comment by saratvemulapalli** [comment]
@joshpalis thanks for the issue. Could help us understand the sequence of events and what are we solving with this proposal?

**Comment by joshpalis** [comment]
Closed as this has been handled by : https://github.com/opensearch-project/opensearch-sdk-java/issues/274
