### ISSUE TITLE
[Feature/extensions] Replace all CountDownLatches and CompletableFuture .get() calls

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/opensearch-sdk-java#292]
In order to make requests asynchronous, all CountDownLatches and CompletableFuture .get() calls must be removed from the extensions framework.  Potential solutions include the CompletableFuture methods .orTimeout() or .join().

**Comment by dbwiddis** [comment]
Looking further into this, seems `.join()` is blocking just like `.get()`.  The primary difference is the exception handling.

But `.orTimeout()` is a non-blocking async call and should be used (with appropriate handling of the exceptionally completed future on timeout or interruption).
