### ISSUE TITLE
[FEATURE] Create ScriptExtension interface

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#318]
### Is your feature request related to a problem?

The `getScriptEngine()` and `getContexts()` extension points communicate an extension's script capabilities to OpenSearch.

### What solution would you like?

Add a new interface `ScriptExtension` with the above two methods, with default implementations matching `ScriptPlugin.java`.

**Comment by dbwiddis** [comment]
@petiveriaalliacea please self-assign this, or just comment here so I can assign it to you, since you've already got the PR in progress.

**Comment by petiveriaalliacea** [comment]
Hello! I guess I can't self-assign this. Thank you!

**Comment by dbwiddis** [comment]
Done in #534
