### ISSUE TITLE
[FEATURE]Create CircuitBreakerExtension interface

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/opensearch-sdk-java#322]
**Is your feature request related to a problem?**

Extension points (see https://github.com/opensearch-project/opensearch-sdk-java/issues/315) will be (optionally) implemented on Extensions. Eventually these points may need to be communicated to OpenSearch to be registered in the appropriate service or module.

Allowing extensions to inherit from appropriate interfaces depending on their type will match the current Plugin implementation.

**What solution would you like?**

Add a new interface CircuitBreakerExtension with default implementations for extension points matching CircuitBreakerPlugin.java.

**Comment by nassipkali** [comment]
Hello @dbwiddis, I would like to take this issue

**Comment by nassipkali** [comment]
@dbwiddis Can we close this issue?
