### ISSUE TITLE
[FEATURE]Create EngineExtension interface 

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/opensearch-sdk-java#323]
**Is your feature request related to a problem?**

Extension points (see https://github.com/opensearch-project/opensearch-sdk-java/issues/315) will be (optionally) implemented on Extensions. Eventually these points may need to be communicated to OpenSearch to be registered in the appropriate service or module.

Allowing extensions to inherit from appropriate interfaces depending on their type will match the current Plugin implementation.

**What solution would you like?**

Add a new interface EngineExtension with default implementations for extension points matching EnginePlugin.java.

**Comment by minalsha** [comment]
@varuntumbe  thank you for contributing toward this project. Could you please assign this issue to yourself since you mentioned that you will work on it? Thanks.

**Comment by dbwiddis** [comment]
@minalsha Actually I think #319 was what @varuntumbe was planning on working next.

**Comment by dbwiddis** [comment]
Apparently GitHub doesn't let us assign people who aren't in the org unless they've commented on the issue.

So, @varuntumbe see if you can assign yourself. If not, just make a comment here and then it will let me assign you.

**Comment by varuntumbe** [comment]
Yes I was going to say that, Its not showing any option to assign it myself. Please assign it to me whenever you get free time.

Thanks and regards
Varun

**Comment by dbwiddis** [comment]
Funny, I was in another dialogue trying again and suddenly it worked.  Then came here to see you'd commented. 🤣 

Thanks again for stepping up to take on these issues, and let us know if you need help.

**Comment by varuntumbe** [comment]
Sure @dbwiddis .

My Full time job blocks me about 10 hours daily but I am hoping to give 1 to 2 hours daily and some more during weekends and to learn more about the Java ecosystem

Thanks and regards
Varun

**Comment by minalsha** [comment]
thank you @varuntumbe  for your contributions.
