### ISSUE TITLE
[FEATURE] Create MapperExtension interface

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/opensearch-sdk-java#327]
**Is your feature request related to a problem?**

Extension points (see https://github.com/opensearch-project/opensearch-sdk-java/issues/315) will be (optionally) implemented on Extensions. Eventually these points may need to be communicated to OpenSearch to be registered in the appropriate service or module.

Allowing extensions to inherit from appropriate interfaces depending on their type will match the current Plugin implementation.

**What solution would you like?**

Add a new interface MapperExtension with default implementations for extension points matching MapperPlugin.java.

**Comment by Kuanysh-kst** [comment]
Hello @dbwiddis, I would like to take this issue

**Comment by Kuanysh-kst** [comment]
#544

**Comment by Kuanysh-kst** [comment]
#546

**Comment by dbwiddis** [comment]
> Can I consider this issue finished?

It's linked to this issue so it will automatically close when the PR is merged.  No further action from you, but our review process requires two approvals.
