### ISSUE TITLE
[FEATURE] Create RepositoryExtension interface

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/opensearch-sdk-java#329]
**Is your feature request related to a problem?**

Extension points (see #315) will be (optionally) implemented on Extensions. Eventually these points may need to be communicated to OpenSearch to be registered in the appropriate service or module.

Allowing extensions to inherit from appropriate interfaces depending on their type will match the current Plugin implementation.

**What solution would you like?**

Add a new interface RepositoryExtension with default implementations for extension points matching RepositoryPlugin.java.

**Comment by kokibas** [comment]
Hello @dbwiddis, I would like to take this issue

**Comment by kokibas** [comment]
Hello @dbwiddis I would like to take this issue

**Comment by kokibas** [comment]
#563

**Comment by kokibas** [comment]
@dbwiddis I would like to ask a question about your video on this link https://youtu.be/26EXeg1l7yE?t=880 when creating an extension.yml file I didn't understand exactly where it needs to be located could you please specify the path to the project where it should be located

**Comment by kokibas** [comment]
@dbwiddis I would like to ask a question about your video on this link https://youtu.be/26EXeg1l7yE?t=880 when creating an extension.yml file I didn't understand exactly where it needs to be located could you please specify the path to the project where it should be located since I don't have the /install/opensearch-3.0.0-SNAPSHOT file in the distribution/archives/linux-tar/build directory/

**Comment by dbwiddis** [comment]
Hey @kokibas I just re-watched the video and somehow the screenshots of the log (around 20:00) aren't being shown.  I may have made a mistake in the screen sharing!

But the main point is, if it's not loading you can look at the log file for a line indicating where it's looking for extensions.yml and not finding it, and that is your directory.

In my macOS install it's here:
```
~/git/OpenSearch/distribution/archives/darwin-tar/build/install/opensearch-3.0.0-SNAPSHOT/extensions
```
That directory may not exist if you haven't done a build, so you have to install it yourself.  The `darwin-tar` part is a macOS thing, you may have a linux equivalent (`linux-tar`).

**Comment by kokibas** [comment]
@dbwiddis #564

**Comment by kokibas** [comment]
Hi @dbwiddis , I finally figured out git #586, can you check please
