### ISSUE TITLE
[FEATURE] Create ReloadableExtension interface 

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/opensearch-sdk-java#330]
**Is your feature request related to a problem?**

Extension points (see #315) will be (optionally) implemented on Extensions. Eventually these points may need to be communicated to OpenSearch to be registered in the appropriate service or module.

Allowing extensions to inherit from appropriate interfaces depending on their type will match the current Plugin implementation.

**What solution would you like?**

Add a new interface ReloadableExtension with default implementations for extension points matching ReloadablePlugin.java.

**Comment by nrakhay** [comment]
Hello! 

Currently I'm considering to take this issue, but I have some questions:

I have looked for similar issues in closed section, and it seems not that hard. However, I couldn't get where to find the ReloadablePlugin.java or the source to which I should refer while working on the issue. Could you please navigate me through this a bit?

**Comment by dbwiddis** [comment]
Hey @nrakhay the plugin interfaces are on the OpenSearch repo:
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/ReloadablePlugin.java

**Comment by nrakhay** [comment]
Oh, I see. 

May you assign me to this one?

**Comment by nrakhay** [comment]
Can you see my PR?
