### ISSUE TITLE
[FEATURE] Publish snapshot following pushes to main rather than on a schedule

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#343]
### Is your feature request related to a problem?

SNAPSHOT versions allow developers to consume the latest `main` branch version from the Central Repository without having to fork and publish locally.

However, the current implementation publishes SNAPSHOT builds every 12 hours via cron.  This is problematic for a few reasons:
 - It may be up to 12 hours stale depending on the timing of the publishing; developers have to wait for fixes
 - It publishes identical snapshots even when there are no changes; developers waste time seeing what may have changed and waste resources downloading an identical dependency to one they have cached
 - It does not check whether the latest push is "broken"; developers relying on the latest snapshot may end up downloading broken artifacts.

### What solution would you like?

1. Remove the current snapshot schedule.
2. Publish SNAPSHOT immediately following a push to the `main` branch that successfully passes a `gradle check`.

### What alternatives have you considered?

 - Adding conditionals to the scheduled workflow to test whether code has changed in the last 12 hours

### Do you have any additional context?

The schedule could be considered in the future when there are a high volume of pushes to main, but is unnecessary now.

**Comment by saratvemulapalli** [comment]
Thanks @dbwiddis for writing this up. We just started with twice a day[1] but seems like on push to main is the best way for us going forward. Infact @gaiksaya wanted to do on push, I was the one who asked for twice a day :) to start with as its not a oneway door but I agree on push makes more sense. 

[1]https://github.com/opensearch-project/opensearch-build/issues/3011#issuecomment-1376464216

**Comment by dbwiddis** [comment]
Here's [an example (maven, not gradle) github workflow](https://github.com/oshi/oshi/blob/master/.github/workflows/sonatype.yaml) to publish snapshots on push to main, that can probably be used as a template.

**Comment by saratvemulapalli** [comment]
@dbwiddis do you want me to pick this up?

**Comment by dbwiddis** [comment]
Sure, it's not a high priority, though.

**Comment by owaiskazi19** [comment]
@dbwiddis does https://github.com/opensearch-project/opensearch-sdk-java/pull/472 resolves the issue?

**Comment by dbwiddis** [comment]
Yep!
