### ISSUE TITLE
Migrate Delete Detector results to SDK using SDKRestClient

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#378]
### Is your feature request related to a problem?
 
Part of https://github.com/opensearch-project/OpenSearch/issues/5224
 
### What solution would you like?
 
Migrate the Delete Detector results Rest API to Extensions SDK using SDKRestClient.
 
Use the implementation of #353 as a reference.  Add new issues for any steps you skip.
 
Implement the following API endpoints:
 - [ ] `DELETE _plugins/_anomaly_detection/detectors/results`

**Comment by owaiskazi19** [comment]
API: DELETE localhost:9200/_extensions/_ad-extension/detectors/results

```
{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "detector_id": {
              "value": "XqAwu4cBQBVk3lUtpDvr"
            }
          }
        }
      ]
    }
  }
}
```

Response:
```
{
    "took": 304,
    "timed_out": false,
    "total": 20,
    "updated": 0,
    "created": 0,
    "deleted": 20,
    "batches": 1,
    "version_conflicts": 0,
    "noops": 0,
    "retries": {
        "bulk": 0,
        "search": 0
    },
    "throttled_millis": 0,
    "requests_per_second": -1.0,
    "throttled_until_millis": 0,
    "failures": []
}
```
