### ISSUE TITLE
Migrate Get Detector stats to SDK using SDKRestClient

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#382]
### Is your feature request related to a problem?
 
Part of https://github.com/opensearch-project/OpenSearch/issues/5224
 
### What solution would you like?
 
Migrate the Get Detector stats Rest API to Extensions SDK using SDKRestClient.
 
Use the implementation of #353 as a reference.  Add new issues for any steps you skip.
 
Implement the following API endpoints:
 - [x] `GET _plugins/_anomaly_detection/stats`
 - [x] `GET _plugins/_anomaly_detection/<nodeId>/stats`
 - [x] `GET _plugins/_anomaly_detection/<nodeId>/stats/<stat>`
 
 
 The Get detector stats api's are responsible for providing information about how the plugin is performing.
 

- [x]  Add components required for RestStatsAnomalyDetectorExtension in createComponents Extension Point in AnomalyDetectorExtension
- [x]  Modify RestStatsAnomalyDetectorExtension Constructor
- [x]  Replace clusterservice to sdkclusterservice
- [x]  Implement TransportAction in StatsAnomalyDetectoTransportAction 
- [x]  Implement getClusterStats and getNodeStats changes
- [x]  Test the above api's

**Comment by vibrantvarun** [comment]
Added necessary objects in create components but there is a method named **stats** missing in SDKIndicesClient which needs to be created on Opensearch-sdk-java.

**Comment by minalsha** [comment]
As per @vibrantvarun , this issue is blocked on resolving this bug: #654 . @dbwiddis / @owaiskazi19 thoughts?

**Comment by dbwiddis** [comment]
> As per @vibrantvarun , this issue is blocked on resolving this bug: #654 . @dbwiddis / @owaiskazi19 thoughts?

Per [this comment](https://github.com/opensearch-project/opensearch-sdk-java/issues/654#issuecomment-1501015726) #654 is not an actual bug, there was an incorrect base path used.  However, in the process of troubleshooting I did implement deprecated and replaced routes in #666, which should be merged and this PR rebased to the new format (closer to original AD format/minimize the diff).

**Comment by vibrantvarun** [comment]
curl -X GET "localhost:9200/_extensions/_ad-extension-1/stats/"
```
{
  "anomaly_detectors_index_status": "non-existent",
  "anomaly_detection_state_status": "non-existent",
  "single_entity_detector_count": 0,
  "detector_count": 0,
  "multi_entity_detector_count": 0,
  "anomaly_detection_job_index_status": "non-existent",
  "models_checkpoint_index_status": "non-existent",
  "anomaly_results_index_status": "non-existent",
  "nodes": {
    "ad-extension-1": {
      "ad_execute_request_count": 0,
      "models": [
        
      ],
      "ad_canceled_batch_task_count": 0,
      "ad_hc_execute_request_count": 0,
      "ad_hc_execute_failure_count": 0,
      "model_count": 0,
      "ad_execute_failure_count": 0,
      "ad_batch_task_failure_count": 0,
      "ad_total_batch_task_execution_count": 0,
      "ad_executing_batch_task_count": 0
    }
  }
}
```
