### ISSUE TITLE
[BUG] java.security.AccessControlException: access denied ("java.io.FilePermission" "<path/to/extensions/folder>" "read") on Node Bootstrap

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/opensearch-sdk-java#390]
### What is the bug?

When running an OpenSearch node with the helloWorld extension using `./bin/opensearch` I receive the following error message:

```
java.security.AccessControlException: access denied ("java.io.FilePermission" "<OPENSEARCH_HOME>/distribution/opensearch-3.0.0-SNAPSHOT/extensions" "read")
```

As a temporary solution, I am able to re-create a local distribution of opensearch after adding these lines to `security.policy`

```
permission java.io.FilePermission "<OPENSEARCH_HOME>/distribution/opensearch-3.0.0-SNAPSHOT/extensions", "read";
permission java.io.FilePermission "<OPENSEARCH_HOME>/distribution/opensearch-3.0.0-SNAPSHOT/extensions/-", "read";
```

OpenSearch should startup and be able to read `extensions/` and `extensions/extensions.yml` without an AccessControlException.

### How can one reproduce the bug?

1. Create a local distribution of OpenSearch: `./gradlew localDistro`
2. Navigate to the local distro. For me its `cd ./distribution/archives/darwin-tar/build/install/opensearch-3.0.0-SNAPSHOT`
3. Enable extensions feature flag by adding `opensearch.experimental.feature.extensions.enabled: true` to `config/opensearch.yml` (Wait for https://github.com/opensearch-project/OpenSearch/pull/6082 to be merged to fix a bug in reading from `opensearch.yml`)
4. Create `extensions/extensions.yml`
5. Start the node using `./bin/opensearch`

### What is your host/environment?

Mac OS X

### Do you have any additional context?

I have tried running `chown -R <my_user> extensions/`, without success

**Comment by saratvemulapalli** [comment]
Thanks @cwperks for opening up the issue. I was able to reproduce the problem on my machine. 
Looks like we are gating the security policy[1] by feature flag but the feature flags are instantiated way later which is why they are not applied. I'll open a PR to take care of this.

[1] https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/bootstrap/Security.java#L320

**Comment by saratvemulapalli** [comment]
Change merged to 2.x: https://github.com/opensearch-project/OpenSearch/pull/6574
