### ISSUE TITLE
[FEATURE] Add identity/authorization headers into Rest Client calls

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#430]
### Is your feature request related to a problem?

Presently `SDKClient` rest calls do not include security features.   Upcoming integration of identity features will include authentication and/or identity tokens that will need to be included with REST requests via the client.

See https://github.com/opensearch-project/OpenSearch/issues/3846

### What solution would you like?

SDKClient REST calls need to edit the `RequestOptions` to add headers.

There may be a need to close/re-initialize the clients or just change the headers, that will need to be determined later.

**Comment by kokibas** [comment]
Hello @dbwiddis , I would like to take this issue

**Comment by dbwiddis** [comment]
Hey @kokibas happy for you to work on this, but I'll be honest the requirement is a little vague here.  Let me know if you have any questions!

**Comment by kokibas** [comment]
@dbwiddis have identity features been completed?

**Comment by kokibas** [comment]
Hello @dbwiddis ,I wanted to ask In order to change Request Options and add headers, I need to call the "toBuilder()" method of the RequestOptions class in SDKClient class , creating a new instance of the Builder class containing the current parameters that can be changed. Then I have to call the Builder methods to add headers to Request Options. Finally, the modified Request Options can be set in the request by calling the "set Request Options()" method.Can you tell me if I understood the task correctly.

**Comment by dbwiddis** [comment]
> Hello @dbwiddis ,I wanted to ask In order to change Request Options and add headers, I need to call the "toBuilder()" method of the RequestOptions class in SDKClient class , creating a new instance of the Builder class containing the current parameters that can be changed. Then I have to call the Builder methods to add headers to Request Options. Finally, the modified Request Options can be set in the request by calling the "set Request Options()" method.Can you tell me if I understood the task correctly.

Yes, I believe that is the correct approach.  [Here is code in a test class doing that.](https://github.com/opensearch-project/OpenSearch/blob/e4d9fb50b74a0b4e7f9b7bb1315e92c1f136efde/client/rest/src/test/java/org/opensearch/client/RequestOptionsTests.java#L73-L82)

**Comment by kokibas** [comment]
@dbwiddis I created the "addheader()" method in /opensearch-sdk-java/src/main/java/org.opensearch.sdk/SDKCleint.java and in this method I call "toBuilder()" for the RequestOptions object obtained from the request object. I didn't understand how to communicate with RequestOptions, which is located in OpenSearch .

**Comment by kokibas** [comment]
@dbwiddis Could you explain, if I should call the "to builder()" method in "Opensearch-SDK-Java/SDKclient", and in fact I haven't found where the SDK client is used to send requests

**Comment by dbwiddis** [comment]
Done in #613
