### ISSUE TITLE
[FEATURE] Code coverage reports for SDK

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#48]
### Is your feature request related to a problem?
As we are making progress, we should start publishing our code coverage reports. 

### What solution would you like?
We use codecov.io for OpenSearch project[1]. We could use JaCoCo to collect these results and push them to codecov.

[1] https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#code-coverage-collecting

**Comment by mloufra** [comment]
The Codecov comment is running successfully. https://github.com/opensearch-project/opensearch-sdk-java/pull/123#issuecomment-1237642742
