### ISSUE TITLE
Add SDKClusterSettings support for extensions.

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/opensearch-sdk-java#503]
### Is your feature request related to a problem?
Anomaly Detection Extension will require support to instantiate new `SDKClusterSetting` objects for use in test classes in which the method `clusterService.getClusterSettings()` is stubbed to return a particular instance of `ClusterSettings`. Currently the `SDKClusterService` contains the `SDKClusterSettings` class [here](https://github.com/opensearch-project/opensearch-sdk-java/blob/f5f65e6dece734d9d7edca131703bc99cd15664b/src/main/java/org/opensearch/sdk/SDKClusterService.java#L62) that merely simulates the `addSettingsUpdateConsumer` method.  Some examples can be found [here](https://github.com/search?q=repo%3Aopensearch-project%2Fanomaly-detection+%22new+ClusterSettings%28%22&type=code)  

### Do you have any additional context?
Example use case for ClusterSettings
```
clusterService = mock(ClusterService.class);
clusterSettings = new ClusterSettings(
        Settings.EMPTY,
        Collections.unmodifiableSet(new HashSet<>(Arrays.asList(AnomalyDetectorSettings.FILTER_BY_BACKEND_ROLES)))
);
when(clusterService.getClusterSettings()).thenReturn(clusterSettings);
```

**Comment by dbwiddis** [comment]
Also
```java
        clusterSettings.updateDynamicSettings(newSettings, target, Settings.builder(), "test");
        clusterSettings.applySettings(target.build());
```

**Comment by dbwiddis** [comment]
New pattern for the request above:
```diff
  settings = Settings.EMPTY;
- ClusterSettings clusterSettings = new ClusterSettings(
-     Settings.EMPTY,
-     Collections
-         .unmodifiableSet(
-             new HashSet<>(Arrays.asList(AnomalyDetectorSettings.MAX_ENTITIES_FOR_PREVIEW, AnomalyDetectorSettings.PAGE_SIZE))
-         )
- );
+ List<Setting<?>> settingsList = List.of(AnomalyDetectorSettings.MAX_ENTITIES_FOR_PREVIEW, AnomalyDetectorSettings.PAGE_SIZE);
+ ExtensionsRunner mockRunner = mock(ExtensionsRunner.class);
+ Extension mockExtension = mock(Extension.class);
+ when(mockRunner.getEnvironmentSettings()).thenReturn(settings);
+ when(mockRunner.getExtension()).thenReturn(mockExtension);
+ when(mockExtension.getSettings()).thenReturn(settingsList);
+ SDKClusterSettings clusterSettings = new SDKClusterService(mockRunner).getClusterSettings();
  when(clusterService.getClusterSettings()).thenReturn(clusterSettings);
```
