### ISSUE TITLE
[BUG] Backport PRs duplicate gradle build and wrapper validation actions

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#538]
### What is the bug?

Backport PRs trigger Gradle Wrapper validation actions and Build checks on both `push` and `pull_request`.

### How can one reproduce the bug?

Let the trigger-bot generate a backport build.

### What is the expected behavior?

Each workflow runs exactly once.

### What is your host/environment?

GitHub Actions

### Do you have any screenshots?

<img width="605" alt="Screenshot 2023-03-08 at 8 55 39 AM" src="https://user-images.githubusercontent.com/9291703/223778112-41e80442-8678-4758-b7ca-5462c15e1db6.png">

### Do you have any additional context?

We had a similar problem with the renovate version updates (or any bot update that creates a branch).  We simply need to add a `branches-ignore` entry for the backport branches like this:
https://github.com/opensearch-project/opensearch-sdk-java/blob/30759d25379ae8dc9d1bb2aad542b61a545e32cc/.github/workflows/build.yml#L2-L5

**Comment by kokibas** [comment]
Hello @dbwiddis , I would like to take this issue

**Comment by dbwiddis** [comment]
Please do, @kokibas !  I'm getting tired of these emails! :)
