### ISSUE TITLE
[FEATURE] Create SDKDiscoveryNodeFilterer class to use within AnomalyDetectionIndices

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/opensearch-sdk-java#540]
### Is your feature request related to a problem?
Anomaly Detection provides the class [DiscoveryNodeFilterer](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/util/DiscoveryNodeFilterer.java) which is used to filter unwanted node types within the cluster. This is then passed to many created components such as [AnomalyDetectionIndices](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java).

Currently for AnomalyDetection Extension, the lack of a node filter prevents specifying a custom result index when creating a detector. This workflow is triggered by [IndexAnomalyDetectorTransportAction](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportAction.java) when a result index is specified within the request body. This eventually utilizes `AnomalyDetectionIndices` to invoke [initCustomResultIndexAndExecute](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java#L328) which attempts to determine the number of primary shards to set per hot node for this particular index request [here](https://github.com/opensearch-project/anomaly-detection/blob/fd547014fdde5114bbc9c8e49fe7aaa37eb6e793/src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java#LL567C24-L567C24).

The number of primary shards is calculated [here](https://github.com/opensearch-project/anomaly-detection/blob/fd547014fdde5114bbc9c8e49fe7aaa37eb6e793/src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java#L575), which uses the node filter to determine the number of eligible data nodes within the cluster .

**Comment by saratvemulapalli** [comment]
Thanks @joshpalis for writing this up. 
It makes sense for AD but do you think this util class will be used by other extensions? If so its a right candidate to put into the SDK if not extension should maintain this.

**Comment by dbwiddis** [comment]
Hmm, when I first saw this I thought it was already an OpenSearch class.   

However the functionality into it does seem like something that should be optimized in general for extensions (visibility into OpenSearch nodes).
