### ISSUE TITLE
[BUG] Miscellaneous Spotbugs issues

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#552]
### What is the bug?

SpotBugs has identified some issues we should fix.

### How can one reproduce the bug?

1. Temporarily install the spotbugs gradle plugin in build.gradle:
```groovy
plugins {
  id "com.github.spotbugs" version "5.0.13"
}
```

2. Run `gradle check`
3. Filter out intentional issues.

### What is the expected behavior?

No unintended bugs

### Do you have any additional context?

Each of these should be evaluated and fixed.

 - [ ]  Exception is caught when Exception is not thrown in org.opensearch.sdk.handlers.UpdateSettingsRequestHandler.handleUpdateSettingsRequest(UpdateSettingsRequest)  At UpdateSettingsRequestHandler.java:[line 105]
 - [ ]  Uninitialized read of extensions in new org.opensearch.sdk.handlers.ExtensionDependencyResponseHandler()  At ExtensionDependencyResponseHandler.java:[line 41]
 - [ ]  Self assignment of field ExtensionDependencyResponseHandler.extensions in new org.opensearch.sdk.handlers.ExtensionDependencyResponseHandler()  At ExtensionDependencyResponseHandler.java:[line 41]
 - [ ]  Found reliance on default encoding in org.opensearch.sdk.TransportCommunicationIT$1.run(): new java.io.PrintStream(OutputStream)  At TransportCommunicationIT.java
 - [ ]  Found reliance on default encoding in org.opensearch.sdk.TransportCommunicationIT$1.run(): new java.io.InputStreamReader(InputStream)  At TransportCommunicationIT.java
 - [ ]  Should org.opensearch.sdk.TestBaseExtension$TestExtension be a _static_ inner class?  At TestBaseExtension.java:[lines 28-30]
 - [ ]  Should org.opensearch.sdk.TestExtensionRestHandler$NoOpExtensionRestHandler be a _static_ inner class?  At TestExtensionRestHandler.java:[lines 18-22]
 - [ ]  org.opensearch.sdk.ExtensionsRunnerForTest.NODE_NAME isn't final but should be  At ExtensionsRunnerForTest.java:[line 19]
 - [ ]  org.opensearch.sdk.ExtensionsRunnerForTest.NODE_HOST isn't final but should be  At ExtensionsRunnerForTest.java:[line 20]
 - [ ]  org.opensearch.sdk.ExtensionsRunnerForTest.NODE_PORT isn't final but should be  At ExtensionsRunnerForTest.java:[line 21]

**Comment by Kuanysh-kst** [comment]
Hello @dbwiddis, I would like to take this issue

**Comment by dbwiddis** [comment]
All yours, @Kuanysh-kst.  Thanks for stepping up!

**Comment by Kuanysh-kst** [comment]
#582
