### ISSUE TITLE
[FEATURE] Initialize SDKClient with instance of ExtensionSettings

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#556]
### Is your feature request related to a problem?

The `SDKClient` constructor takes no arguments. 

This requires either a host address and port, or the `ExtensionSettings`, to be passed via parameters to initialize other clients.  This client is only ever instantiated once, and we have a copy of the ExtensionSettings when we do so.

### What solution would you like?

1. Add a parameter to the `SDKClient` constructor taking an instance of `ExtensionSettings` and saving it as an instance field
2. Use that instance field to either replace (my preference) or overload (I won't complain) `initializeJavaClient(ExtensionSettings settings)`, `initializeJavaAsyncClient(ExtensionSettings settings)` and `initializeRestClient(ExtensionSettings settings)`.

### What alternatives have you considered?

Status quo.

**Comment by Kuanysh-kst** [comment]
Hello @dbwiddis, I would like to take this issue

**Comment by dbwiddis** [comment]
All yours, @Kuanysh-kst ... note there's an Open PR #558 you'll want to let get merged and sync with main before you start.  Hopefully that'll happen later today.

**Comment by Kuanysh-kst** [comment]
I closed it because the previous commit also got into PR

**Comment by Kuanysh-kst** [comment]
#579

**Comment by dbwiddis** [comment]
Fixed in #579
