### ISSUE TITLE
[FEATURE] Integrate Async Java Client

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#557]
### Is your feature request related to a problem?
To invoke the Actions residing in OpenSearch. Extensions will use Java Client to call the action using REST requests available. Currently, we support synchronous Java Client. As AD plugin uses asynchronous request calls, create an async Java Client for the same.

### What solution would you like?
opensearch-java supports OpenSearchAsyncClient. Create a SDKClient wrapper for the same.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
Duplicate of #296 :-)

**Comment by owaiskazi19** [comment]
> Duplicate of #296 :-)

Ah! Didn't realize. Will close this one
