### ISSUE TITLE
[PROPOSAL] Deliverables for Create Detector for AD Extension

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#59]
### What are you proposing?
1. Comment out all the code of the AD plugin and have only the create detector code for AD. Make sure the build is successful and AD plugin is able to run the feature create detector.
2. For creating the detector, 
    - Let's just focus on [CreateIndexRequest](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java#L535) by sending a request to OpenSearch consisting of `ANOMALY_DETECTORS_INDEX` and let OpenSearch create the index.
   - Also, an [ActionListener](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportAction.java#L94) to detect the failure if any. 

       ![create](https://user-images.githubusercontent.com/16099877/180574302-03373464-6d82-42c0-a156-e3d4dee94e3f.jpg)

3. As we are not focusing on Security in the first phase of deliverable
   - We will comment out the user validation and also avoid using `FILTER_BY_BACKEND_ROLES` role required currently for AD plugin
   - Since SDK will be our client to make a request call to OpenSearch. We can comment out the `client` currently present in the AD plugin codebase
4. Integrate SDK with AD plugin and make it run as an extension with OpenSearch

**Comment by dbwiddis** [comment]
> We will comment out the user validation and also avoid using FILTER_BY_BACKEND_ROLES role required currently for AD plugin

Instead of commenting user out, we can pass `null` as user for now, which bypasses the role filtering.  See #23

> Since SDK will be our client to make a request call to OpenSearch. We can comment out the client currently present in the AD plugin codebase

This could either be replaced by a null placeholder or dozens of method signatures need to be rewritten to remove this parameter.  Discuss on #22.

**Comment by dbwiddis** [comment]
Hey @owaiskazi19 can this issue be closed now that we've created the detector?
