### ISSUE TITLE
[BUG] Hello World sample validator reverses logic

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#591]
### What is the bug?

A sample validated setting was added to the HelloWorld extension in #421.  It is based on original assumptions that a matching validator would fail.  During review of the companion PR, the implementation reversed the logic so it now does the opposite of what's intended.

The unit test was missing the `@Test` annotation so it wasn't being adequately tested, as I noticed when reviewing code coverage.

### How can one reproduce the bug?

1. Add the `@Test` annotation to `TestHelloWorldExtension` method `testValidatedSettings()`.
2. Run `gradle check`

### What is the expected behavior?

Tests pass.

### Do you have any additional context?

Possible resolutions:
1. (Easy) Change the regular expression from "forbidden" to one that verifies a word doesn't exist.  This is a [confusing regex](https://stackoverflow.com/questions/406230/regular-expression-to-match-a-line-that-doesnt-contain-a-word): "^((?!forbidden).)*$"
2. (Preferred) Update the validator to take a boolean parameter switching between "fail if it matches" or "fail if it doesn't match".  This provides the most flexibility.

Bonus points:
 - Add more validated settings like IP address matching

**Comment by Kuanysh-kst** [comment]
Hello @dbwiddis, I would like to take this issue

**Comment by dbwiddis** [comment]
>  I think I can temporarily remove the first 3 lines of this method to make this issue(I get an error because of this line: final String expected = randomAlphaOfLengthBetween(1, 5);)

Yes, just remove that. It works on OpenSearch but we don't have the right setup for it to work for us.  Just pick a test string of your own.

**Comment by Kuanysh-kst** [comment]
https://github.com/opensearch-project/OpenSearch/pull/6823

**Comment by dbwiddis** [comment]
Done in #608 and https://github.com/opensearch-project/OpenSearch/pull/6823
