### ISSUE TITLE
[FEATURE] Move all the extensions interface under a same directory

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#599]
### Is your feature request related to a problem?
Current, the extension interfaces are under `org.opensearch.src` directly, we can create a directory under `src`, call it as `extensions` and move these files under it. Also, we have to take care of moving the tests with the same pattern

1. [PersistentTaskExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/ScriptExtension.java)
2. [ReloadableExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/ReloadableExtension.java)
3. [IndexStoreExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/IndexStoreExtension.java)
4. [ScriptExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/ScriptExtension.java)
5. [IngestExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/IngestExtension.java)
6. [IndexStoreExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/IndexStoreExtension.java)
7. [SearchExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/SearchExtension.java)
8. [SystemIndexExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/SystemIndexExtension.java)
9. [MapperExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/MapperExtension.java)
10. [RepositoryExtension](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/RepositoryExtension.java)

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by kokibas** [comment]
Hello @owaiskazi19 , I would like to take this issue

**Comment by kokibas** [comment]
@dbwiddis Can you be more specific about this issue?

**Comment by dbwiddis** [comment]
I think src is meant to be sdk. @owaiskazi19 ?

**Comment by dbwiddis** [comment]
We also have the interfaces in #600 and #601 that will need to have PR merged and moved before this gets done.

And someone is working on #318, #321, and #324 which this would conflict with.  

Would like to hold off on this until all the individual interfaces are written.

And I'm not sure I really like the package name `org.opensearch.sdk.extensions`.  Would be nice to come to agreement on the package name while we're waiting.

**Comment by owaiskazi19** [comment]
@dbwiddis sure. Let's hold on to this until we have all the interfaces merged. Also, open to discuss about the package name.

**Comment by dbwiddis** [comment]
SInce we're putting interfaces there, and the interfaces define the API, why not `api`?  [reference example](https://techhub.hpe.com/eginfolib/networking/docs/sdn/sdnc2_7/5200-0910prog/content/s_sdnc-app-recommended-package-names.html)

**Comment by kokibas** [comment]
@dbwiddis I think I can create a PR for this problem if we have a name for the directory
