### ISSUE TITLE
[FEATURE] Publish sources and javadoc with the release JAR

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#615]
### Is your feature request related to a problem?

While trying to build an extension from scratch, I wanted to use the features in my IDE to look at the code I was using (in eclipse, hover over a class and right-click "Open Declaration").  Rather than seeing the source code for the declaration, I saw only a textual representation of the compiled class, which wasn't very helpful.  Also there was no javadoc for the methods I was trying to use.

### What solution would you like?

Support IDE-driven development by including source and javadoc jars with releases (including snapshots).

### What alternatives have you considered?

Requiring people to read the javadocs (where are they published?) or grok the actual code from GitHub (ugh!)

### Do you have any additional context?

Looks like some instructions on how to do this [here](https://stackoverflow.com/questions/21904269/configure-gradle-to-publish-sources-and-javadoc/58845587#58845587).

![Screenshot 2023-03-27 at 9 43 28 AM](https://user-images.githubusercontent.com/9291703/228008471-a4b95389-67ae-46a7-a5a7-51a12396bed1.png)

![Screenshot 2023-03-27 at 9 44 12 AM](https://user-images.githubusercontent.com/9291703/228008624-62750d35-3e2a-4bf8-a2b4-f29b1b86edf5.png)

**Comment by kokibas** [comment]
@dbwiddis I would like to take this issue

**Comment by dbwiddis** [comment]
All yours, @kokibas!
