### ISSUE TITLE
[FEATURE] Integrate historical Anomaly Detection analysis

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#636]
### Is your feature request related to a problem?

Historical Analysis crosses over multiple REST APIs and needs to be integrated into existing workflows.

### What solution would you like?

Implement workflow branches for:
 - [x] `GET _plugins/_anomaly_detection/detectors/<detectorId>?task=true`
 - [x] `POST _plugins/_anomaly_detection/detectors/<detectorId>/_start` with body `{"start_time": 1633048868000, "end_time": 1633394468000}`
 - [x] `POST _plugins/_anomaly_detection/detectors/<detectorId>/_stop?historical=true`
 - [x] `POST _plugins/_anomaly_detection/detectors/tasks/_search` with `"task_type": "HISTORICAL_HC_DETECTOR"`
 - [x] `GET _plugins/_anomaly_detection/detectors/<detectorId>/results/_topAnomalies?historical=true`
 - [x] `GET _plugins/_anomaly_detection/detectors/<detectorId>/_profile/ad_task`

**Comment by kokibas** [comment]
Hello @dbwiddis , I would like to take this issue

**Comment by joshpalis** [comment]
The following have been completed by https://github.com/opensearch-project/anomaly-detection/pull/880

-  `POST _plugins/_anomaly_detection/detectors/<detectorId>/_start with body {"start_time": 1633048868000, "end_time": 1633394468000}`
-  `POST _plugins/_anomaly_detection/detectors/<detectorId>/_stop?historical=true`

**Comment by joshpalis** [comment]
The following has been completed by https://github.com/opensearch-project/opensearch-sdk-java/issues/451

- `GET _plugins/_anomaly_detection/detectors/<detectorId>?task=true`

**Comment by joshpalis** [comment]
The following has been completed by https://github.com/opensearch-project/opensearch-sdk-java/issues/381

- `GET _plugins/_anomaly_detection/detectors/<detectorId>/_profile/ad_task`
