### ISSUE TITLE
[FEATURE] [META] Register RestHandlers in OpenSearch

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#64]
### Is your feature request related to a problem?
Currently, extensions are initialized in OpenSearch through extensions.yml file. For OpenSearch to process any functionality of the extension be it creating an index, deleting it or any other extension's functionality, the REST APIs of the extension should be registered in OpenSearch (ExtensionsOrchestrator) for OpenSearch to understand which extension it should send request to after receiving it from the user. The RestHandler should do the job of registering those APIs and map it in the sample format mentioned below
```
{extensionNode1: [API1, API2, API3], extenionNode2: [API1, API4, API5]}
```
extensionNode will be the node of the extension and values will be the APIs of the extension.

This issue requires us to
1. Register extension REST APIs to ExtensionOrchestrator by building Rest Handler model [3][4]
2. Map the extension node with the APIs it has  to register [6] [7]
3. Process the API call sent by the user and send a transport request to the right extension which has the request registered for that API [5] [8]

![Rest_new](https://user-images.githubusercontent.com/16099877/181392993-c9a82238-83a2-42d4-99f9-f26afaae657b.png)

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
Some quick questions:
 - You have "OpenSearch SDK" labeled on the Extension, but my understanding is that the SDK is what will define how the extension and OpenSearch communicate with each other.  So my thought is the SDK would be more appropriate either on the ExtensionsOrchestrator (as the "receiving end of the arrows coming from the extensions", with the "SDK Client" fulfilling a similar role for the Extension), or as some sort of dotted-line box around all the back-and-forth communication (1, 2, 3, 8, and 9) indicating the common language that both sides need to understand. 
 - I'm not sure how the user interaction (5) falls into the sequence.  Should they be triggering the bootstrap request (1) with all the index information needed, or does the index information come from the extension, or both?

**Comment by dbwiddis** [comment]
I've created separate issues to track this.
 - [ ] #68 
 - [ ] #69 
 - [ ] #70

**Comment by dbwiddis** [comment]
> {extensionNode1: [API1, API2, API3], extenionNode2: [API1, API4, API5]}

@owaiskazi19 two questions on this mapping:
 - Is it multiple extensions that will use the API or just multiple nodes? e.g., is API1 in the list above associated with the same extension running on multiple nodes?
 - Wouldn't it make more sense to make the APIs the key and a list of nodes as the value? e.g.,
`{API1: [extensionNode1, extensionNode2], API2: [extensionNode1], API3: [extensionNode1], API4: [extensionNode2], API5: [extensionNode2]}`

**Comment by dbwiddis** [comment]
**Log messages documenting the process**

Register request:
```
15:39:38.584 [opensearch[sample-extension][generic][T#1]] INFO  org.opensearch.sdk.ExtensionsRunner 
 - Sending Register REST Actions request to OpenSearch for [GET /api_1, PUT /api_2, POST /api_3]
15:39:38.584 [opensearch[sample-extension][generic][T#1]] INFO  org.opensearch.transport.TransportService 
 - TransportService:sendRequest action=internal:discovery/registerrestactions
15:39:38.585 [opensearch[sample-extension][generic][T#1]] INFO  org.opensearch.transport.TransportService 
 - Action: internal:discovery/registerrestactions
```

Sent immediately following response to initialize the extension (2 and 3 from diagram):
```
15:39:38.587 [opensearch[sample-extension][transport_worker][T#5]] TRACE org.opensearch.transport.TransportService.tracer 
 - [3][internal:discovery/extensions] sent response
15:39:38.587 [opensearch[sample-extension][transport_worker][T#8]] TRACE org.opensearch.transport.TransportService.tracer 
 - [3][internal:discovery/registerrestactions] sent to [{dev-dsk-widdisd-2a-8f5e7316.us-west-2.amazon.com
}{VPMZuSmfTLSJmqP2W8iOrg}{-vDwLtVyRi2Z9CtPjCHfjg}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true}] (timeout: [null])
```

On the OpenSearch node, registered (4 on diagram):
```
[39:38,592][INFO ][o.o.e.r.RestSendToExtensionAction] Registering: GET /_extensions/_opensearch-sdk-1/api_1
[39:38,593][INFO ][o.o.e.r.RestSendToExtensionAction] Registering: PUT /_extensions/_opensearch-sdk-1/api_2
[39:38,593][INFO ][o.o.e.r.RestSendToExtensionAction] Registering: POST /_extensions/_opensearch-sdk-1/api_3
```

Response received by SDK:
```
15:39:38.609 [opensearch[sample-extension][generic][T#4]] INFO  org.opensearch.sdk.handlers.RegisterRestActionsResponseHandler 
 - received Registered extension opensearch-sdk-1 to handle REST Actions [GET /api_1, PUT /api_2, POST /api_3]
```

Response to REST requests (5 on diagram).  `api_1` is successful:

> (16:15:41) <0> [~]  % curl localhost:9200/_extensions/_opensearch-sdk-1/api_1
> Forwarding the request GET /api_1 to {sample-extension}{opensearch-sdk-1}{opensearch-sdk-1}{sdk_host}{127.0.0.1:4532}{dimr}%

Mapped to the correct extension (6, 7, 8 on diagram):
```
16:15:42.011 [opensearch[sample-extension][generic][T#2]] INFO  org.opensearch.sdk.ExtensionsRunner 
 - The extension would have just executed GET /api_1
```

Other requests receive appropriate error messages (_2 and _3 have registered URI but not method, _4 is not registered):

> (16:16:59) <0> [~] % curl localhost:9200/_extensions/_opensearch-sdk-1/api_2
> {"error":"Incorrect HTTP method for uri [/_extensions/_opensearch-sdk-1/api_2] and method [GET], allowed: [PUT]","status":405}%
> 

> (16:17:05) <0> [~] % curl localhost:9200/_extensions/_opensearch-sdk-1/api_3
> {"error":"Incorrect HTTP method for uri [/_extensions/_opensearch-sdk-1/api_3] and method [GET], allowed: [POST]","status":405}%

> (6:17:07) <0> [~]  % curl localhost:9200/_extensions/_opensearch-sdk-1/api_4
> {"error":"no handler found for uri [/_extensions/_opensearch-sdk-1/api_4] and method [GET]"}%
