### ISSUE TITLE
[BUG] Backport workflow seems to have broken backports

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#659]
### What is the bug?

After updating to `VachaShah/backport@v2.2.0`, backport workflows are failing.

### How can one reproduce the bug?

Merge a PR.  Observe the backport workflow fail.

See: https://github.com/opensearch-project/opensearch-sdk-java/actions/workflows/backport.yml

### What is the expected behavior?

Backport workflow completes.

### What is your host/environment?

GitHub Actions.

### Do you have any screenshots?

> Run VachaShah/backport@v2.2.0
>   with:
>     github_token: ***
>     head_template: backport/backport-<%= number %>-to-<%= base %>
>     body_template: Backport <%= mergeCommitSha %> from #<%= number %>.
>     label_pattern: ^backport (?<base>([^ ]+))$
>     labels_template: []
>     title_template: [Backport <%= base %>] <%= title %>
> Warning: Your repository allows merge commits and rebase merging.
>  However, Backport only supports rebased and merged pull requests with a single commit and squashed and merged pull requests.
>  Consider only allowing squash merging.
>  See https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github for more information.
> Backporting 97d51f4b176745defe9f115[2](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4635720409/jobs/8202999379#step:3:2)6fff22a45faf7e5f from #65[3](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4635720409/jobs/8202999379#step:3:3).
> /usr/bin/git show -s --format='%an' 97d51f[4](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4635720409/jobs/8202999379#step:3:4)b17674[5](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4635720409/jobs/8202999379#step:3:5)defe9f1152[6](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4635720409/jobs/8202999379#step:3:6)fff22a45faf[7](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4635720409/jobs/8202999379#step:3:7)e5f
> fatal: not a git repository (or any of the parent directories): .git
> Error: Error: The process '/usr/bin/git' failed with exit code 12[8](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4635720409/jobs/8202999379#step:3:8)

### Do you have any additional context?

Mostly posting this for situational awareness. I assume 2.2.0 has a bug and we should either revert to 2.1.0, or wait for 2.3.0, and in the meantime we should be alert when we merge PRs to manually backport them.

CC: @VachaShah

**Comment by VachaShah** [comment]
Hi @dbwiddis, I am working on fixing this issue. In the meantime, can you please revert to 2.1.0? Thank you!

**Comment by owaiskazi19** [comment]
@dbwiddis https://github.com/opensearch-project/opensearch-sdk-java/pull/661
