### ISSUE TITLE
[FEATURE] Reduce boilerplate for empty JSON "OK" responses

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#721]
### Is your feature request related to a problem?

Success for many REST requests results in a response with status OK (200) and an empty JSON object (`{}`).

There is lots of boilerplate code generating this.  Plugin code looks like:
```java
XContentBuilder contentBuilder = r.toXContent(channel.newBuilder().startObject(), ToXContent.EMPTY_PARAMS);
contentBuilder.endObject();
channel.sendResponse(new BytesRestResponse(RestStatus.OK, contentBuilder));
```
In extensions we are migrating this to:
```java
XContentBuilder contentBuilder = r.toXContent(JsonXContent.contentBuilder().startObject(), ToXContent.EMPTY_PARAMS);
contentBuilder.endObject();
ExtensionRestResponse extensionRestResponse = new ExtensionRestResponse(request, RestStatus.OK, contentBuilder);
```
Each `r` in the above snippets is a different sort of Response object (usually); but all implement the `ToXContent` interface.

In addition, we also have this code repeated often, using the above `contentBuilder` instance:
```java
ExtensionRestResponse extensionRestResponse = new ExtensionRestResponse(request, RestStatus.OK, contentBuilder);
```

### What solution would you like?

Create some constants/methods in the `BaseExtensionRestHandler` to reduce or eliminate the boilerplate.  I believe (this is untested code) that something like the following would create the `XContentBuilder` object:
```java
import org.opensearch.core.xcontent.ToXContent;

public static XContentBuilder EMPTY_JSON_XCONTENT = (new ToXContent() {
    @Override  
    toXContent(XContentBuilder builder, Params params) throws IOException {
        builder.endObject();
        return builder;
    }).toXContent(JsonXContent.contentBuilder().startObject(), ToXContent.EMPTY_PARAMS);
}
```
(Note that you could probably move `startObject()` next to `endObject()`; I only copied the above to stay somewhat true to the original code.)

Once that is created, you could also have a canned "ok" response, possibly:
```java
protected ExtensionRestResponse okNoContent(RestRequest request) {
     return new ExtensionRestResponse(request, RestStatus.OK, EMPTY_JSON_XCONTENT);
}
```

### What alternatives have you considered?

The `RestResponse` (and by extension (literally in more than one way) the `ExtensionRestResponse` class) permits you to just specify the content type, and the content as a `String`, so this could also work, possibly faster, and we wouldn't need the whole builder.  While this would work, I don't like hardcoding constants like this so prefer the above approach.
```java
protected ExtensionRestResponse okNoContent(RestRequest request) {
     return new ExtensionRestResponse(request, RestStatus.OK, "application/json; charset=UTF-8", "{}");
}
```

### Do you have any additional context?

Coming from https://github.com/opensearch-project/anomaly-detection/pull/881/files#r1181795885 and https://github.com/opensearch-project/anomaly-detection/pull/881/files#r1181857497

**Comment by nassipkali** [comment]
@dbwiddis I would like to take this issue

**Comment by dbwiddis** [comment]
COmpleted in #736
