### ISSUE TITLE
[FEATURE] Integration Tests for HelloWorld Extension

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#740]
### Is your feature request related to a problem?
As we are building the test framework, we should write integration tests for HelloWorld extension to verify the functionality. 

Coming from a conversation of HelloWorld is broken with changes merged in OpenSearch server. 
We dont test helloworld in our CIs and we should. 

cc: @cwperks @ryanbogan

**Comment by minalsha** [comment]
@joshpalis  assigning this issue to you since you were working on it.
