### ISSUE TITLE
[BUG] Build publishing broken due to duplicate artifacts

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#798]
### What is the bug?

Since merging #687, snapshot publication [is broken](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/5137886278/jobs/9246561020):
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishMavenJavaPublicationToSnapshotsRepository' not found in root project 'opensearch-sdk-java'.
```

Also, possibly related, unable to publish to `mavenLocal()`.
```
> Task :publishNebulaPublicationToMavenLocal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishNebulaPublicationToMavenLocal'.
> Failed to publish publication 'nebula' to repository 'mavenLocal'
   > Invalid publication 'nebula': multiple artifacts with the identical extension and classifier ('jar', 'sources').
```
Reverting the associated commit 04d9eab8ca08acca572f258053e05e18809adf4b allows publishing.  

### How can one reproduce the bug?

`./gradlew publishToMavenLocal`

### What is the expected behavior?

```
BUILD SUCCESSFUL in 8s
9 actionable tasks: 9 executed
```
### Do you have any additional context?

This PR also broke `gradle run`, see #789 (this was known before merge, but the additional failures were not)

**Comment by owaiskazi19** [comment]
Raised https://github.com/opensearch-project/opensearch-sdk-java/pull/799 to revert the change. Meanwhile, @ryanbogan can address the above issue and push new change for integ test framework.
