### ISSUE TITLE
[Meta] [FEATURE] Add getActions support for AD

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#80]
### Is your feature request related to a problem?
As we are building extension support for AD, we need to add support for getActions. 

`getActions` enables plugins to register custom transport actions. 
With extensions, SDK should be able to support registering transport actions and proxy them to the extension when a transport action is invoked.

- [x] #105
- [x] #106
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/119

**Comment by dbwiddis** [comment]
Hey @owaiskazi19 I think there may be some overlap between this and the approach I'm taking on #69.  Can you clarify whether that's somewhat the same thing or if not, how this differs from what I'm doing there?

**Comment by saratvemulapalli** [comment]
Taking a stab at this. 
`getActions` is an interface to enable plugins to define custom transportActions[1].

For extensions, we should enable them to create custom transport actions. 
Here is the workflow which could solve this problem:

1. As @dbwiddis added support for Rest APIs in https://github.com/opensearch-project/opensearch-sdk-java/issues/64, Extension would use a similar API to register transportActions.
2. `ExtensionsOrchestrator` will register the list of actions with `ActionModule`[2] with a unique transport action handler per extension.
3. `ExtensionsOrchestrator` will respond with Ack to the extension.
4. When a transport request comes along, the registry looks up and will make a call to `ExtensionsOrchestrator`. 
5. `ExtensionsOrchestrator` will make a transport API call to the extension to process the request. 

I would like to split up this issue into 3 pieces:
1. `ExtensionsOrchestrator` to handle register Transport Actions
2. SDK to make a request to OpenSearch and register actions.
3. Dynamically register transport actions in `ActionModule`


[1] https://github.com/opensearch-project/OpenSearch/blob/1bfabed0780c228f4f3c9a26aac2169e361c9426/server/src/main/java/org/opensearch/plugins/ActionPlugin.java#L82 
[2] https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/ActionModule.java#L509

**Comment by saratvemulapalli** [comment]
Removed #107 out of the meta issue as registering dynamic actions was not really needed as proxy actions added support for whats needed for setting up Anomaly Detection Plugin as an extension. 
We'll revive the PR after create detector .
