### ISSUE TITLE
[BUG] Extension should not bind to its hostname

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#815]
### What is the bug?

During initialization, an extension binds to its port on the network interface associated with the host name:
https://github.com/opensearch-project/opensearch-sdk-java/blob/5fed5642c9f728d9d67099a0a38cba58a419d968/src/main/java/org/opensearch/sdk/ExtensionsRunner.java#L162

It is possible for an extension to be listening on multiple interfaces. In particular, the localhost interface will be different than an externally-facing one; it's also possible to have a different interface associated with private and public IP addresses.  These may not be known in advance when starting up the extension.

### How can one reproduce the bug?

1. Start up an extension such as Hello World on a remote node with the default settings (127.0.0.1).
2. Attempt to connect to the extension on its configured port.

### What is the expected behavior?

Connection established on its listening port.

### Do you have any additional context?

On OpenSearch, there are separate settings for `BIND_HOST` and `PUBLISH_HOST`.  There is no assigned host/IP for `BIND_HOST`:
```java
    public static final Setting<List<String>> BIND_HOST = listSetting(
        "transport.bind_host",
        HOST,
        Function.identity(),
        Setting.Property.NodeScope
    );
```
where
```java
    public static final Setting<List<String>> HOST = listSetting(
        "transport.host",
        emptyList(),
        Function.identity(),
        Setting.Property.NodeScope
    );
```

The extension should probably set `BIND_HOST` to this same `HOST` (essentially an empty list), or bind to "0.0.0.0" which listens on all network interfaces.  We could/should also set `PUBLISH_HOST` to the existing value from the settings.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue

**Comment by dbwiddis** [comment]
Hey @tarunsamanta2k20 are you still working on this?

**Comment by tarunsamanta2k20** [comment]
@dbwiddis could you please suggest me how to do it?

**Comment by tarunsamanta2k20** [comment]
@dbwiddis I am interested to work on it. Can I do pairing for this issue?

**Comment by dbwiddis** [comment]
The line of code you need to fix is documented above.  Change `BIND_HOST` to `PUBLISH_HOST` in that line, and add a new similar line for `BIND_HOST` which uses the builder's `putList(String setting, List<String> values)` method with an empty list.

**Comment by tarunsamanta2k20** [comment]
I couldn't set the second argument like that as it expects a path, not a list.
**Collections.emptyList()**

**Comment by dbwiddis** [comment]
Use pitList, not put. :)
