### ISSUE TITLE
[BUG] Overriding SDK DEBUG logging configuration is needlessly difficult

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#824]
### What is the bug?

The SDK contains a logging configuration file, `log4j2.xml` in `src/main/resources` which puts it on the class path of all extensions.  It is currently set to DEBUG level logging at the root level and has an extra ERROR level for netty, which we've since removed.

https://github.com/opensearch-project/opensearch-sdk-java/blob/ab2a3038a8c1f0cc266ec4ed23e4f07e0dd80b6f/src/main/resources/log4j2.xml#L11-L17

Extensions importing the SDK end up with this file on the classpath.  This logging configuration is not obvious to them, nor easily accessible without digging through the GitHub source code.  

More importantly, it is more difficult to override locally; users need to figure out how to configure their own config file and pass a command line parameter or set a system property to override the one on the class path.  Simply adding another config file doesn't always work, as the file extensions play a part in which one is chosen first.  Specifically, the priority (which no one ought to be expected to know) is:
1. Value of `log4j2.configurationFile` system property or command line argument.
2. `.properties` file on class path
3. `.yaml` file on the class path
4. `.json` file on the class path
5. `.xml` file on the class path.
6. Default log4j settings (ERROR level).

If there's multiple files and a tie, which one is loaded first is based on class loading order, which in my experience has tended to be the SDK.

### How can one reproduce the bug?

1. Run an extension.
2. Look at the logs, and observe lots of DEBUG statements.

### What is the expected behavior?

Extensions should use the default Log4j2 settings with no configuration file on the class path.

### Do you have any additional context?

Suggested solution:
 - rename the `log4j2.xml` configuration file to one that is not automatically added to the class path
 - update build.gradle or developer guide command line instructions on how to point to the updated config file

One other thought: we are locking extension authors into using Log4J2 as their logger.  We might consider changing our logging to the SLF4J API, which allows extension authors to plug in their own logging framework of choice.  So we could use log4j2 in our own build.gradle for testing but extension authors could use logback, reload4j, slf4j-simple, log4j2, etc.

**Comment by dbwiddis** [comment]
Option 1: Leave logger as-is and document.

1. build.gradle changes:
    - Need to an an exclusion to the Java Client dependency to exclude the slf4j-api transitive dependency.
2. Need to add verbiage to developer guide indicating that we inherit an API dependency on log4j2 from OpenSearch and link to log4j2 documentation on how to configure logging.
3. Need to rename our own DEBUG logging xml file and configure build.gradle commands to set the environment variable pointing to it.

Option 2: Switch to SLF4J

1. build.gradle changes:
    - Need to add an api dependency to slf4j-api (we already get from clients but they may go away later)
    - Need to add a runtie dependency to slf4j-log4j2-impl
    - Need to an an exclusion to the OpenSearch dependency to exclude the log4j2-api transitive dependency.    
2. Need to add verbiage to developer guide indicating that we use SLF4J and they can add their own choice logger with a link to SLF4J docs.
3. Need to rename our own DEBUG logging xml file and configure build.gradle commands to set the environment variable pointing to it.
```

There are no code changes required for Option 2: SLF4J has its own minimal implementation of LogManager and Logger that delegate the logging calls to SLF4J.  SO Option 2 is nearly identical to Option 1 with only a few extra imports in build.gradle and what I think is easier to write documentation.

**Comment by dbwiddis** [comment]
(Also note in the xml file there' s a stray `i` in the XML and the netty classes aren't there any more for special treatment.  So tweaking the file in addition to the rename might be welcome.)

**Comment by dbwiddis** [comment]
For context on why I think this is important and why we have to pick one of the two options:
1. We are placing a log4j configuration file on the class path.  This overrides default/expected logging behavior for any dependency (extension authors), immediately giving them DEBUG logging to both console and log file named `application-${date:yyyyMMdd}.log`, with a specified timestamp, without any clear documentation on how to override this behavior (and in fact, preventing them from overriding with an xml file; they would have to use another file format higher in priority).
2. In the current implementation SDK is exposing two different logging APIs (`log4j-api` and `slf4j-api` (transitively via clients)).  Both slf4j API and log4j API have the same package/class names for `org.apache.log4j.LogManager` and `org.apache.log4j.Logger`.  **This is the very definition of jar hell**. This means the following situation would occur:
   - A downstream user could implement SLF4J with their own preferred logger that's not log4j, such as logback.
   - SDK logging implementing the above packages would arbitrarily pick one of the two packages to use the implementation from.  The slf4j-api would delegate to the user's chosen logger, while our own implementation would use our own settings (or a user's format if they figure out how to override), and logging destinations would be unpredictable. 
   - For non-modular projects, this unpredictable behavior happens. For projects using JPMS, this won't even compile, without the user debugging enough to know they have to exclude packages from either SDK or OpenSearch.

**Comment by minalsha** [comment]
@saratvemulapalli  can you please share progress on this issue? Thanks

**Comment by dbwiddis** [comment]
Since this issue is changing hands a few times and I'd like it completed today if possible, I've done some exploration to figure out the exact things that need to be done.  These are the exact changes needed to exclude SLF4J, the fastest way to resolve this for the upcoming release.  I'll add another issue to propose switching to SLF4J at a later time.

Get `log4j2.xml` off the class path with that reserved name:
1. Rename it.  I propose `log4j2-sdk.xml`
2. Fix the typo (stray i) inside it and remove the separate Netty config that's no longer needed.

Make the following changes in `build.gradle`:
1. Exclude all transitive imports from slf4j:
```groovy
configurations.all {
    exclude group: 'org.slf4j'
}
```
2. Remove all other references to slf4j versions (the version param and override lower in `configurations`)
3. Create a system property in any gradle task that we want to use logging, to reference the new logfile location.  For example for hello world:
```groovy
task helloWorld(type: JavaExec) {
  group = 'Execution'
  description = 'Run HelloWorld Extension.'
  mainClass = 'org.opensearch.sdk.sample.helloworld.HelloWorldExtension'
  classpath = sourceSets.main.runtimeClasspath 
   
  systemProperty 'log4j2.configurationFile', 'log4j2-sdk.xml'
}
```
Do similarly for any other task (possibly test, but not really sure... hello world may be sufficient.)

Add documentation:
1. Somewhere in the developer guide that we use log4j2 logging, and link to https://logging.apache.org/log4j/2.x/manual/configuration.html

**Comment by dbwiddis** [comment]
OK, @vibrantvarun tried to implement both options above, and hit hard blockers on both paths.

1. Switching everything to use log4j and exclude slf4j failed because Apache HTTP dependency uses classes from slf4j.   
2. Switching everything to use slf4j and exclude log4j failed because OpenSearch Settings.builder() uses classes from log4j.

To resolve this issue for the release, @vibrantvarun is just going to rename the log file, see #885.

I'll open a new issue to try to untangle all these dependencies at a later date.

CC: @saratvemulapalli @owaiskazi19
