### ISSUE TITLE
[BUG] Package extension.yml file

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/opensearch-sdk-java#86]
### What is the bug?
Building and running the opensearch-sdk artifact would look for the `extension.yml` file within the `opensearch-sdk/build/distributions/opensearch-sdk-1.0.0-SNAPSHOT/src/test/resources/` directory instead of the `opensearch-sdk/src/test/resources` directory

### How can one reproduce the bug?
Run `./gradlew build` in the `opensearch-sdk` directory to produce the artifact. Navigate to `opensearch-sdk/build/distributions/` and untar the generated artifact using `tar -xvf opensearch-sdk-1.0.0-SNAPSHOT.tar`. Navigate to `opensearch-sdk-1.0.0-SNAPSHOT/` and run `./bin/opensearch-sdk`

This will produce the following error : 
`Exception in thread "main" java.io.FileNotFoundException: src/test/resources/extension.yml (No such file or directory)`

In order to fix this issue, we must create the directory within the package and generate the extension.yml file here so that the artifact has access.

EDIT: Following discussion, the extensions.yml file will be moved to the config directory where opensearch.yml is currently stored.

**Comment by dbwiddis** [comment]
This is not as simple as just changing the directory paths.  

Both "file paths" are accessible with the current setup but neither file path will work in a compiled jar file.

The file should be moved to `src/main/resources` which will put it at the root of the classpath.  You'll then have to use some variant of `getResource()` or `getResourceAsStream()` from the classloader, such as:
```java
// reads from the root of the classpath so will find something in src/main/resources
InputStream in = this.getClass().getClassLoader().getResourceAsStream("extension.yml");
// or get the filepath
Path ymlPath = this.getClass().getClassLoader().getResource("extension.yml").getPath();
```

You can also get it from the class itself using NIO, but this is relative to the package, so if you're in the `org.opensearch.sdk` package you need to navigate up 3 directories:
```java
// reads from the root of the package
Path ymlPath = Paths.get(this.getClass().getResource("../../../extension.yml").toURI());
// or
File ymlFile = new File(this.getClass().getResource("../../../extension.yml").toURI());
// I think if you lead with a slash you can work around the relative package directory things, so try
Path ymlPath = Paths.get(this.getClass().getResource("/extension.yml").toURI());
// or
String ymlPath = this.getClass().getResource("../../config/dev/example.xml").getPath();
```
or variations of the above.

One other complication for using the classpath:  anyone else can have a same-named file on the class path and they will conflict.  So a generic name like `extension.yml` is going to be problematic.  To work around this:
 - put it in a subdirectory in `src/main/resources` that a user is unlikely to also have in their own classpath, e.g., `src/main/resources/org/opensearch/sdk` (which is essentially like putting it in the package anyway!)
 - give it a more verbose name like `opensearch_sdk_extension.yml`

**Comment by dbwiddis** [comment]
See this commit for implementation for a different YAML file: https://github.com/opensearch-project/opensearch-sdk-java/pull/74/commits/821d27f0409b6b6c92970d53e2744eda1dcab0e7

**Comment by dbwiddis** [comment]
The changes in #109 may make this obsolete. Review discussion on that PR before spending any time on this.
