### ISSUE TITLE
[BUG] Integration Test Framework broken

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#867]
### What is the bug?
```
./gradlew clean build integTest
```
Integ Test framework is broken for extensions and SDK.

- Fix Init sequence for extension integTest
- Fix all tests in `TransportCommunicationIT.java`
- Add new integration tests for HelloWorld extension.
- Add this integration test as part of CI (Github actions)

**Comment by minalsha** [comment]
@joshpalis  is the IT framework fixed now?
