### ISSUE TITLE
[FEATURE] Use java-client 3.0.0 when available

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk-java#89]
### Is your feature request related to a problem?
Currently, SDKClient uses opensearch-java client 2.0.0 version. Use 3.0.0. when the next java client version is available.

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by minalsha** [comment]
has dependency on https://github.com/opensearch-project/opensearch-java/issues/205

**Comment by owaiskazi19** [comment]
> I think the feature would be to use the java client version that is compatible with OpenSearch v3.0. The client version could be a lower major version number that is forward compatible to a higher server version.

Hey @wbeckler! This issue mainly talks about updating the java-client version to 3.0 from 2.0 when available. Currently, for SDKClient which in turns uses java-client we are using 2.0 version and the OpenSearch version is 3.0.

**Comment by minalsha** [comment]
@wbeckler  are you going to be updating the java-client version to 3.0 from 2.0? Or are you confirming here: https://github.com/opensearch-project/opensearch-sdk-java/issues/89#issuecomment-1225828647 that java-client version 2.0 should work with OpenSearch version 3.0?

**Comment by wbeckler** [comment]
It's not known yet what the major version of the java client will be that is compatible with server version 3.0, since the client version and server versions don't always match.

**Comment by dblock** [comment]
To this point, does it make sense to depend on the java client from the SDK? Maybe lower level REST client should be used instead?

**Comment by owaiskazi19** [comment]
Upgraded java client to 3.0.0-SNAPSHOT here: https://github.com/opensearch-project/opensearch-sdk-java/pull/231.
Upgrade was needed to handle client transports to Apache HttpClient/Core5.x.

**Comment by saratvemulapalli** [comment]
> To this point, does it make sense to depend on the java client from the SDK? Maybe lower level REST client should be used instead?

Do you think that would be better? I honestly don't know how the low level client is used, I presume it understands internal data structures of OpenSearch more than Java Rest Client. 
So it probably means relying on a high level abstraction (interms of RestAPIs) will keep extensions protected from OpenSearch core changes.
