### ISSUE TITLE
[BUG] Instructions to `./gradlew run -Dopensearch.experimental.feature.extensions.enabled=true` don't enable extensions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-sdk-java#916]
### What is the bug?

Running `./gradlew run -Dopensearch.experimental.feature.extensions.enabled=true` does not pass through `opensearch.experimental.feature.extensions.enabled=true` and therefore doesn't enable extensions feature flag.

### How can one reproduce the bug?

Read https://github.com/opensearch-project/opensearch-sdk-java/blob/5f9b9b372d6fb5d6562c0dbce4cabf249436ca63/DEVELOPER_GUIDE.md#option-2 that says to run the following.

```
./gradlew run -Dopensearch.experimental.feature.extensions.enabled=true
```

Doesn't pickup `opensearch.experimental.feature.extensions.enabled`.

```
$ 
osx ~/source/opensearch-project/openseach-sdk-py/dblock (main)$ curl -X POST localhost:9200/_extensions/initialize -H "Content-Type:application/json" -d'{}'
{"error":"no handler found for uri [/_extensions/initialize] and method [POST]"}
```

### What is the expected behavior?

Extensions feature flag to be enabled.

### What is your host/environment?

Mac OS

**Comment by dbwiddis** [comment]
Seems the ability to pass feature flags on the command line is intended to be removed and only supported in opensearch.yml, reading comments on https://github.com/opensearch-project/OpenSearch/pull/4959 (which implies the capability is only provided for backwards compatibility).

It does seem possible that `--args="-Dopensearch.experimental.feature.extensions.enabled=true"`  could work but I think that may require the application plugin and I don't see that used.
