### ISSUE TITLE
Rename the namespace for opensearch-sdk-java

### ISSUE THREAD

**Issue by mloufra** [opensearch-project/opensearch-sdk-java#99]
Since the Repo name has been changed from `opensearch-sdk` to `opensearch-sdk-java`, do we need to change the namespace `org.opensearch.sdk` to `org.opensearch.sdk.java` as well ?

**Comment by dbwiddis** [comment]
Arguing in favor of "just sdk" is the `java-client` using the namespace `org.opensearch.client` without any reference to the language.

**Comment by dblock** [comment]
I recommend closing this and leaving `org.opensearch.sdk` without `java` because there needs to be a default JVM SDK and this is it. Even if another java-compatible SDK were to be evolved in, for example, Kotlin, it would probably want a distinct alternate namespace like `org.opensearch.sdk.v2`.
